### ISSUE TITLE
routing issue with mounted engine

### ISSUE THREAD

**Issue by Maroo-b** [code-and-effect/effective_email_templates#10]
Hello,

I got an error when trying the step 5 from the readme

> Visit localhost:3000/admin/email_templates in your browser to edit templates

It seems that the routes aren't loaded when mounting the engine here is a screenshot from available routes:
![effective_email](https://cloud.githubusercontent.com/assets/7128972/14375101/0188a8ee-fd5e-11e5-8c11-10580ed50a91.png)

The test was made using:
- Ruby 2.3
-  Rails 4.2.x

**Comment by matt-riemer** [comment]
Hey @Maroo-b,

Thanks for noticing and submitting this Issue!   I will update the documentation accordingly.

I have to verify still, but I'm pretty sure the correct path would be

`effective_email_templates.admin_email_templates_path`
