### ISSUE TITLE
not working in rails 5.

### ISSUE THREAD

**Issue by naveen1336** [code-and-effect/effective_email_templates#12]
i have setup this gem this error came No route matches [GET] "/admin/email_templates" how to resolve this please help

**Comment by naveen1336** [comment]
no routes added to the routes file

**Comment by matt-riemer** [comment]
Hey @naveen1336 

This gem hasn't been tested in rails 5....it might work!

You might need to also install [effective_datatables](https://github.com/code-and-effect/effective_datatables) to get the admin routes working.

They're only conditionally loaded, as you can see here:
https://github.com/code-and-effect/effective_email_templates/blob/master/config/routes.rb
